### ISSUE TITLE
Updated to 2.3.2 from 1.3.0 now have dataCenter error

### ISSUE THREAD

**Issue by hipitihop** [cronofy/cronofy-node#39]
I updated to v 2.3.2 from 1.3.0 making adjustment to call constructor. But I get the following error. Do I need to pass extra parms/options now or ideas ?

```.../node_modules/cronofy/src/index.js:21
    api: 'https://api' + (config.dataCenter ? '-' + config.dataCenter : '') + '.cronofy.com'
                                ^
.../node_modules/cronofy/src/index.js:21
    api: 'https://api' + (config.dataCenter ? '-' + config.dataCenter : '') + '.cronofy.com'
                                ^

TypeError: Cannot read property 'dataCenter' of undefined
    at new cronofy (.../node_modules/cronofy/src/index.js:21:33)
    at .../run/compiled_dev/parts/hat_node/cronofy.js:12:29
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at nodeGlobalRequire (.../run/compiled_dev/parts/goog/bootstrap/nodejs.js:87:6)
....
Process finished with exit code 1```

**Comment by hipitihop** [comment]
Update: Instead of empty constructor I now pass {"access_token": "...."} and above error is resolved, however now my readEvents is getting no results. I'll have to investigate further what has changed in the API, it's not immediately obvious in readme. Have these changes been docked somewhere ? I assume all this is why you have bumped breaking SEMVER

**Comment by stephenbinns** [comment]
Hi @hipitihop what does you call to readEvents look like?

**Comment by hipitihop** [comment]
@stephenbinns  Unchanged from working in 1.3.0 is this some callback vs promise issue ?
```js
readEvents({"access_token": "...obfuscated...",
             "include_managed": true,
             "only_managed": false,
             "tzid": "Australia/Brisbane",
             "from": "......",
             "to": "....."}, callback-fn)
```

**Comment by stephenbinns** [comment]
Is this still and issue for you @hipitihop?
